### PR TITLE
new bee icons

### PR DESCRIPTION
**Pull request by lmenvs**
## About The Pull Request
CUTE BEES

## Why It's Good For The Game
BEEEEEEEEEEEEEES
TO DO:

- [x] NEW BEE SPRITES
- [x] SOME FRIENDLY MAINTENANCE BEE SPAWN

## Changelog
:cl:
add: NEW YEAR NEW BEES
/:cl:

### CODE REVIEW

**Comment by pitaden** [comment]
Turns out I can click the checkboxes and that edits the PR, woops!
Anyways, **BEEEEEEEES!**

**Review by nednaZ — COMMENTED** [review]
Using the rat code directly will cause them to spawn randomly in engineering, since there are exposed wires there.
Not a huge deal, just pointing out that there will be BIG BEES in places besides maintenance.

If these bees cannot sting, is there a point in assigning them an actual chemical?
Could just give them a randomized color in general instead.

Can these bees attack if directly player controlled?

**Comment by lmenvs** [comment]
> Using the rat code directly will cause them to spawn randomly in engineering, since there are exposed wires there. Not a huge deal, just pointing out that there will be BIG BEES in places besides maintenance.
> 

Moved these to just spawn directly from the maint loot table

> If these bees cannot sting, is there a point in assigning them an actual chemical? Could just give them a randomized color in general instead.
> 

Inherently no, but it was a convenient method of coloring them without messing with their code too much.  I could perhaps allow them to pollinate or let them drop something based on their reagent if killed? 

> Can these bees attack if directly player controlled?

Does not appear so.

**Review by nednaZ — APPROVED** [review]
Looks good to me. Bees as maint loot is truly funny

**Pull request merged**
