### PR TITLE
Rideable Water and Fuel Tanks!

### PR DESCRIPTION
**Pull request by KoboldCommando**
## About The Pull Request

Adds the ability to buckle to water tanks, fuel tanks, and foam tanks.  You can propel yourself with a fire extinguisher while riding one.  They also make sound while moving like an office chair.  It uses the vehicle component to give a proper graphical offset while you're on it.

## Why It's Good For The Game

Enables more silly shenanigans! You can leap onto a tank to shield it from being blown up!  You can ride own down the hall threatening people!  You can strap yourself to a water tank to be an extremely silly firefighter!

## Changelog
:cl:
add: Water and fuel tanks can now be ridden, and make noise when being moved! 
/:cl:

### CODE REVIEW

**Comment by KoboldCommando** [comment]
At Zanden's request, I added the same ride-ability to the nuclear bomb and variants!

**Comment by nednaZ** [comment]
From what it looks like, this entire change could actually be put in the module folder rather than editing the main files themselves.
A quick example would be making the new file "monkestation/code/modules/antagonists/nukeop/equipment/nuclearbomb.dm" and putting the variables in there, as well as the initialize that gives it the riding component.
Just ping me if you want help with that, but it looks like it won't be too hard.

**Comment by Merlin1230** [comment]
Honestly, while these could be moved, I think its better to keep things _with_ the object rather then have all their procs and vars scattered around. Honestly, I'd be fine with the procs moving, just keep the vars with the object declaration.

**Comment by Merlin1230** [comment]
Cammie gave the go ahead to merge

**Pull request merged**
